# Generated by Django 4.2.4 on 2023-09-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='version_name',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='number',
            new_name='version_number',
        ),
    ]
